version: '3.1'
services:
  db:
    image: postgres:13.2 # https://hub.docker.com/_/postgres
    restart: always
    environment:
      # these credentials must be kept in-sync with ormconfig.json
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    volumes: 
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
volumes:
  postgres-data: {}
